export enum JobType {
    ASK = 'ask',
    SUMMARIZE = 'summarize',
    TRANSLATE = 'translate',
    ENTITY_EXTRACTION = 'entity-extraction',
    DATE_EXTRACTION = 'date-extraction',
    KEY_POINT = 'key-point',
    KEYWORDS = 'keywords',
    IMAGE_GENERATE = 'image-generate',
    IMAGE_EDIT = 'image-edit',
    INGEST_CONTENT = 'ingest-content',
    DELETE_VECTORS = 'delete-vectors',
    SEARCH = 'search',
    EMBEDDING = 'embedding',
    RELATIONSHIP_QUERY = 'relationship-query',
    RELATIONSHIP_MODIFY = 'relationship-modify',
    RELATIONSHIP_EXTRACTION = 'relationship-extraction',
    DETECT_LANGUAGE = 'detect-language',
    TRANSCRIBE = 'transcribe',
}
