export enum ExecutionType {
  ASK = 'ask',
  SUMMARIZE = 'summarize',
  TRANSLATE = 'translate',
  ENTITY_EXTRACTION = 'entity-extraction',
  DATE_EXTRACTION = 'date-extraction',
  KEY_POINT = 'key-point',
  KEYWORDS = 'keywords',
  INGEST_CONTENT = 'ingest-content',
  SEARCH = 'search',
  EMBEDDING = 'embedding',
  RELATIONSHIP_EXTRACTION = 'relationship-extraction',
  DETECT_LANGUAGE = 'detect-language',
  TRANSCRIBE = 'transcribe',
}
